### ISSUE TITLE
[Dev UI] Using .default() in defineFlow input schema breaks flow Dev UI 

### ISSUE THREAD

**Issue by DenisVCode** [firebase/genkit#1001]
**Describe the bug**
If you try to use zod `.default()` in `inputSchema` during `defineFlow`, it will make the parameters dissapear from the Flow Dev UI. 

Sample input schema:
```typescript
export const pdfExtractFlow = defineFlow(
  {
    name: "pdfExtractFlow",
    inputSchema: z.object({
      pdfPath: z.string().default("/mypdf.pdf"),
    }),
    outputSchema: LVSchema,
    authPolicy: (auth) => {
      console.log("auth", auth);
    },
  },
  async (inputs) => {...});
```

With the `.default("/mypdf.pdf"),`, this is the UI, missing the parameter:

![image](https://github.com/user-attachments/assets/5fa53563-81b3-49f9-b828-dbd7dd325eef)

Without it, it appears as normal:

![image](https://github.com/user-attachments/assets/decfb1a9-44c1-4659-8b57-f6be843bc33a)

**To Reproduce**
1. Create new flow with string input (I haven't tested other types)
2. Add `.default("/mypdf.pdf"),` to input schema 
3. Refresh the Dev UI
4. The param with .default is missing

**Expected behavior**
The param shouldn't be missing, ideally, the default would be prefilled in the UI. 

**Additional context**
Related discussion on Discord: https://discord.com/channels/1255578482214305893/1255934063173435402/1291404663559553034

**Comment by tonybaroneee** [comment]
Fixed in UI repo.
