### ISSUE TITLE
[JS] ollama embeddings plugin is "misconfigured"

### ISSUE THREAD

**Issue by pavelgj** [firebase/genkit#1080]
Ollama config options have required fields: `modelName` and `serverAddress`

https://github.com/firebase/genkit/blob/2d380039d0ba2628a1645214ee4838371fa3b4a0/js/plugins/ollama/src/embeddings.ts#L2

which means that those two config options must be provided at call time:

```ts
await embed({
  embedder: 'ollama-embedder',
  content: 'foo',
  options: {
    modelName: 'ollama-embedder',
    serverAddress: 'http://localhost:...',
  }
})
```

(and they are actually unused)

Which is not right. Intended usage is:

```ts
export default configureGenkit({
  plugins: [
    ollama({
      embedders: [
        {  name: 'ollama-embedder',  dimensions: 123  },
      ],
      serverAddress: 'http://127.0.0.1:11434', // default local address
    }),
  ],
});

await embed({
  embedder: 'ollama-embedder',
  content: 'foo',
  options: {
    truncate: true,
  }
})
```

the `options` are these: https://github.com/ollama/ollama/blob/main/docs/api.md#parameters-7 (sans model name because it's already provided to `configureGenkit`).

I say `OllamaEmbeddingConfigSchema` must be `.passthrough()` (https://zod.dev/?id=passthrough) and we should just pass all extra/unknown options directly to ollama API as is.

**Comment by cabljac** [comment]
PR which should resolve this: https://github.com/firebase/genkit/pull/1086
