### ISSUE TITLE
[DevUI] Support adding examples to a dataset from trace viewer

### ISSUE THREAD

**Issue by shrutip90** [firebase/genkit#1113]
Designs here:

https://www.figma.com/design/f3te3Yc6XArJP6iIHNqxxC/Genkit-Dev-UI?node-id=1665-9438&t=tMYrcvNNam1nfGAF-4

Add a button in trace view:
![image](https://github.com/user-attachments/assets/d95a1984-c6f7-4621-a686-1f1fd79c5124)

Button should open this dialog listing all the datasets available:
![image](https://github.com/user-attachments/assets/df790bae-8675-4602-850f-c324adca5a1c)

Once the user selects a dataset, the Add button should be enabled:
![image](https://github.com/user-attachments/assets/4e68be80-64ac-4f64-9dde-efb1bfb34091)

Clicking add should add the example to the dataset.

**Comment by mjchristy** [comment]
Designs here:

https://www.figma.com/design/f3te3Yc6XArJP6iIHNqxxC/Genkit-Dev-UI?node-id=1665-9438&t=tMYrcvNNam1nfGAF-4

**Comment by shrutip90** [comment]
Noting down some of the open items here:

- Snack bar messages for success/failure with error details.
- Check if we need an undo option in the success message?
- Update dataset metadata in the store to see the correct number of examples in the last 3 screens here: https://github.com/FirebasePrivate/genkit-ui/pull/1162
- If a user clicks on 'Add to dataset' again, we need to have some way of marking the datasets that already have it and maybe disable them so they cannot add the example twice? (Check with Marissa on the UI)

**Comment by mjchristy** [comment]
As discussed in the meeting:

-  No need to have an undo action
- Users can add to dataset multiple times (we don't check)
- Create new should open the create new modal (within the Trace page), and success toast should say "Trace added to MY_NEW_DATASET"
