### ISSUE TITLE
[Dev UI] [New Nav] Add Breadcrumb bar to the Top Nav

### ISSUE THREAD

**Issue by mjchristy** [firebase/genkit#1133]
**Context**

Navigation within the DevUI actions and traces will now be in a central place.

For example,

my-project > flows > flow-name
my-project > evaluations > eval-id
my-project > traces > trace-id

Model runner
One exception is the models page, which will not have a list page separate from its runner.
my-project > models

**Design Notes**
We will need a new dropdown customized dropdown for this, based on the (-5 density) material dropdown.
The project folder will eventually be a dropdown (likely rarely, as this will only occur).

**Comment by tonybaroneee** [comment]
Completed in https://github.com/FirebasePrivate/genkit-ui/pull/1091/commits/f2e00f9753420c3bbc55360f81e60d95de289718. Project folder will be represented at the top in a follow-up PR (as a separate issue).
