### ISSUE TITLE
[JS] @google-cloud/vertexai 1.9.0 causes tool errors (next branch only?)

### ISSUE THREAD

**Issue by maxl0rd** [firebase/genkit#1134]
**Problem Description**

On next branch, using any vertexai defined model from the dev ui:

Vertex response generation failed: ClientError: [VertexAI.ClientError]: got status: 400 Bad Request. {"error":{"code":400,"message":"Unable to submit request because function parameters schema should be of type OBJECT. Learn more: https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/function-calling","status":"INVALID_ARGUMENT","details":[{"@type":"type.googleapis.com/google.rpc.DebugInfo","detail":"[ORIGINAL ERROR] generic::invalid_argument: Unable to submit request because function parameters schema should be of type OBJECT. Learn more: https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/function-calling [google.rpc.error_details_ext] { message: \"Unable to submit request because function parameters schema should be of type OBJECT. Learn more: https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/function-calling\" }"}]}}

The API signature for including tools in requests has changed to

```
 "tools": [
    {
      "functionDeclarations": [
        {
          "name": string,
          "description": string,
          "parameters": {
            object (OpenAPI Object Schema)
          }
        }
      ]
    }
  ],
```

When including tools in request from the dev ui, the request looks like

```
 "tools": [
    {
      "name": "loadForecastJson",
      "description": "Loads weather forecast data for the given city.",
      "inputSchema": {
        "type": "string",
        "description": "A city name",
        "$schema": "http://json-schema.org/draft-07/schema#"
      },
      "outputSchema": {
        "type": "string",
        "description": "A weather forecast in json format",
        "$schema": "http://json-schema.org/draft-07/schema#"
      }
    },
```

**Resolution**

Happens with @google-cloud/vertexai `1.9.0`, which gets pulled in because the dep is `^1.1.0` .

Fix the behavior below, and set a new minimum version. Consider "pinning" to that version, since semver cannot be trusted?

**Comment by maxl0rd** [comment]
This happens with @google-cloud/vertexai `1.9.0`. This was pulled in because the dep is `^1.1.0` .

**Comment by MichaelDoyle** [comment]
WAI. Looks like functions on Vertex need to take an object, and we are passing string above.
