### ISSUE TITLE
[Dev UI] [New Nav] Adjust trace view layout to accommodate new design

### ISSUE THREAD

**Issue by mjchristy** [firebase/genkit#1139]
The new design requires that we make some changes to the trace viewer layout.

https://www.figma.com/design/f3te3Yc6XArJP6iIHNqxxC/Genkit-Dev-UI?node-id=1221-3903&t=A2QTgWSFjsBXeGN8-4

**Comment by shrutip90** [comment]
Fixed in https://github.com/FirebasePrivate/genkit-ui/pull/1097
