### ISSUE TITLE
[Tooling] Flow runner spins forever if server crashes before response of streaming flow.

### ISSUE THREAD

**Issue by mbleigh** [firebase/genkit#1155]
**Describe the bug**
If the underlying reflection server crashes before a response is received, the flow runner spins forever. It should probably have some kind of timeout / mechanism to show this as an error instead.

**To Reproduce**
1. Build a streaming flow.
2. Run it from the flow runner.
3. Before it completes, crash the server.
4. The UI spins forever.

**Expected behavior**
An error message or timeout.

**Comment by tonybaroneee** [comment]
No longer reproducable. A proper error message is shown immediately in a callout now once the server is crashed:

<img width="1336" alt="Image" src="https://github.com/user-attachments/assets/c9618172-a86d-4aec-a13c-18bec610ce40" />
