### ISSUE TITLE
[Tooling] "Output" of streamed flows seems broken on `next` branch

### ISSUE THREAD

**Issue by mbleigh** [firebase/genkit#1156]
**Describe the bug**
As far as I can tell, streamed flows do not show `output` and do not properly associate with their trace when they complete on the `next` branch right now.

**To Reproduce**
1. Start `testapps/flow-simple-ai` and go to the Dev UI
2. Run `streamFlow` with "pirates" as the input
3. See text stream in and response complete.

**Expected behavior**
When response is complete, **Output** panel remains empty, also "View Trace" button goes to "undefined"

**Comment by MichaelDoyle** [comment]
This is working for me on HEAD. A couple things that maybe you are running into:

- Need to run with `GENKIT_ENV=dev` e.g. `GENKIT_ENV=dev pnpm run start`
- There was a bug where output was not rendered at all that was fixed https://github.com/FirebasePrivate/genkit-ui/pull/1087

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/5496452d-e43d-488a-8cc1-e310407df8be">

<img width="686" alt="image" src="https://github.com/user-attachments/assets/73bc0c7b-3a68-4b49-a861-8fa99683e130">
