### ISSUE TITLE
[Dev UI] [New Nav] Adjust runner pages for the new nav

### ISSUE THREAD

**Issue by mjchristy** [firebase/genkit#1177]
Redesign the runner pages to remove the titles. Titles are available in the breadcrumb bar.

https://www.figma.com/design/f3te3Yc6XArJP6iIHNqxxC/Genkit-Dev-UI?node-id=1148-5772&t=A2QTgWSFjsBXeGN8-4

**Comment by tonybaroneee** [comment]
Done in https://github.com/FirebasePrivate/genkit-ui/pull/1091.
