### ISSUE TITLE
[JS] missing uuid import on 0.9 RC

### ISSUE THREAD

**Issue by cabljac** [firebase/genkit#1184]
**Describe the bug**

Running a simple flow in Next.js (in a test) it complained about missing `uuid`.

I'm not 100% this is a genkit issue, but my flow was just this:

```typescript
import { z } from "genkit";
import { ai } from "../genkit";

export const mainFlow = ai.defineFlow(
  {
    name: "mainFlow",
    inputSchema: z.string(),
    outputSchema: z.string(),
  },
  async (input) => input
);
```

and my test:

```typescript
import { describe, it, expect } from "vitest";
import { mainFlow } from "./mainFlow";

describe("mainFlow", () => {
  it("should run", async () => {
    const result = await mainFlow("hello");
    expect(result).toBe("hello");
  });
});
```

**Expected behavior**
Not to need to install `uuid` as a dependency, probably

**Screenshots**
<img width="441" alt="Screenshot 2024-11-05 at 20 17 41" src="https://github.com/user-attachments/assets/d3553b39-3e9c-49e0-a064-642d6b707120">

**Runtime (please complete the following information):**
 - OS: [MacOS]

** Node version
❯ node --version
v20.11.1

**Additional context**
This is on the 0.9 RC

**Comment by cabljac** [comment]
We found we needed to add `uuid` during testing in [this update](https://github.com/TheFireCo/genkit-plugins/pull/155) as well

**Comment by Gustolandia** [comment]
Adressed in https://github.com/firebase/genkit/pull/1296
