### ISSUE TITLE
[Dev UI] [New Nav] Increase Density of "footer" on model runner

### ISSUE THREAD

**Issue by MichaelDoyle** [firebase/genkit#1208]
Should we have this match / lineup with the height of the footer in the nav panel?

<img width="990" alt="image" src="https://github.com/user-attachments/assets/6b7b734e-fac5-4647-a678-1a594c945c58">

**Comment by tonybaroneee** [comment]
Chatted with Marissa, addressed this w/ https://github.com/FirebasePrivate/genkit-ui/pull/1091/commits/9edf1cc7eb72b5dbadb44cf069f059862cb07674.

<img width="425" alt="image" src="https://github.com/user-attachments/assets/a7dad599-7b04-4b3b-b8b2-0d36d4a229f5">
