### ISSUE TITLE
[Dev UI] Sort actions/flows/etc alphabetically on each page

### ISSUE THREAD

**Issue by MichaelDoyle** [firebase/genkit#1210]
Currently they appear out of order

<img width="1074" alt="image" src="https://github.com/user-attachments/assets/cdde9800-c6cf-42b7-9191-01e6cacf0c93">

**Comment by tonybaroneee** [comment]
Good call, added sorting by name in https://github.com/FirebasePrivate/genkit-ui/pull/1091/commits/1e74d8090cbc32512f6fdead8f5e4e07b438c3f4.
