### ISSUE TITLE
[JS] 0.9 .prompt file issues

### ISSUE THREAD

**Issue by mbleigh** [firebase/genkit#1213]
Running into a number of issues using .prompt files in 0.9 when used as agent tool. Documenting list here.

- [x] Can't use a named `.prompt` as a tool without loading it elsewhere first.
- [x] Even when using it, seems to be incorrectly namespaced under `dotprompt/{name}`
- [x] Even when working around those issues, `@state` is not available to a delegated prompt
- [x] The `description` of prompts is not loaded when used as a tool

**Comment by odbol** [comment]
Another issue: `Model googleai/gemini-1.5-pro-latest not found`

**Comment by pavelgj** [comment]
> Another issue: `Model googleai/gemini-1.5-pro-latest not found`

Try googleai/gemini-1.5-pro
