### ISSUE TITLE
[Dev UI] [New Nav] Show / hide empty runners

### ISSUE THREAD

**Issue by mjchristy** [firebase/genkit#1344]
Considerations

- By default, we always show Models, Flows and Prompts - as these are key building blocks of genkit
- TBD - If Empty (i.e. all menu items have `(0)`), show them all?

Copy:
"View more"
"View less"

How will this interact with runtime connection? We should persist their nav state unless they refresh.

Screenshots

### Collapsed State

![Image](https://github.com/user-attachments/assets/da1ed25c-1f8e-4905-ac47-b50c9ad68437)

Annotations:
<img width="522" alt="Screenshot 2024-11-20 at 2 03 01 PM" src="https://github.com/user-attachments/assets/98eda70b-6381-48ea-9788-f79b2681fa72">

**Comment by tonybaroneee** [comment]
![Image](https://github.com/user-attachments/assets/d0c0ae43-8e02-4b4f-a9f3-d891d7421184)

**Comment by MichaelDoyle** [comment]
Re: persistence, currently we do a "hard refresh" when the connection is re-established. We probably need to revisit that behavior in a more general sense.

**Comment by tonybaroneee** [comment]
FYI - there's already some pre-existing, unused logic in `nav-toggle.service.ts` that you can leverage here. Check out the `areRunnersCollapsed` and `areRunnersCollapsed` helper methods, which use `localStorage` to remember the collapsed/expanded state.

**Comment by hugomurillomtz** [comment]
We can close this one now, right @tonybaroneee?
