### ISSUE TITLE
[JS] Add support for `gemini-1.5-flash-8b` in Vertex AI and Google AI plugins

### ISSUE THREAD

**Issue by apascal07** [firebase/genkit#1367]
https://developers.googleblog.com/en/gemini-15-flash-8b-is-now-generally-available-for-use/

**Comment by chrisraygill** [comment]
Did you mean to label this as JS? JS already supports this model I think

**Comment by louislamlam** [comment]
@chrisraygill  Is the flash-8b model available in 0.9.4 as I couldn't find it.

**Comment by apascal07** [comment]
@louislamlam It's only available via Google AI.

**Comment by louislamlam** [comment]
@apascal07 Got it, thanks for you information.
