### ISSUE TITLE
[Dev UI] [Evals] Add ability to delete datasets from the UI

### ISSUE THREAD

**Issue by mjchristy** [firebase/genkit#1414]
Give the user the ability to delete a dataset

From the list of datasets in a an overflow menu

![Image](https://github.com/user-attachments/assets/c755513c-e4f7-4635-bcf7-4ebfebbcc0cc)

From the Dataset (in the button header)

![Image](https://github.com/user-attachments/assets/f13bacd5-2fdd-488a-a65d-f524edb1fb24)

Add delete confirmation modal if not empty.

Optional to add a new smaller button (32px hight) for that header row.

Link to Figma:
https://www.figma.com/design/f3te3Yc6XArJP6iIHNqxxC/Genkit-Dev-UI?node-id=2263-15835&t=ChFZbr1GnnYE3asm-4

**Comment by shrutip90** [comment]
@mjchristy I am adding a snackbar to say "Deleted dataset successfully" or "Error deleting dataset" but I was not sure how to display the error details. Any ideas?

In the case where we open a confirmation modal for non-empty datasets, one idea is to show error details within the modal and keep it open. We could do the same for empty datasets to keep it simple. Please lmk if you have other ideas.

**Comment by ssbushi** [comment]
Assigning to @shrutip90 for the confirmation part.

**Comment by mjchristy** [comment]
For non-empty datasets, let's show the error in the modal like you said. I think it might make sense for the entire modal to change over to the error modal however. Like the modal is an "error" modal rather than a confirm modal with an error message, that way it could be used for the empty dataset one as well.  

How long will the error be? Because the other more scalable idea might be to simply have a really big toast.
