### ISSUE TITLE
[Dev UI] Endless Loading Spinner in Genkit UI

### ISSUE THREAD

**Issue by Linaks** [firebase/genkit#1435]
**Describe the bug**
I've created a sample genkit codebase with the help of firebase cli (firebase init).
However I can't do anything in the Genkit UI if I start it by `genkit start` because I end in an endless loading spinner:
The text I see is `Waiting to connect to Genkit runtime...`.

**To Reproduce**
1. Create sample genkit codebase with firebase cli (firebase init)
2. Go to the folder which has been created
3. Start genkit with `genkit start`
4. Go to Genkit UI (e.g. http://localhost:4000)

**Expected behavior**
Genkit UI and flows can be tested.

**Screenshots**
<img width="1916" alt="image" src="https://github.com/user-attachments/assets/b40b6a8d-9193-4818-bb61-a022cb506df1">

**Desktop (please complete the following information):**
 - Device: Macbook Pro 16" M2 Pro
 - OS: macOS
 - Browser: Google Chrome
 - Genkit v0.9

**Additional context**
/

**Comment by 553058001** [comment]
I have the same problem, may I ask if you have solved it
