### ISSUE TITLE
[Tooling] Prompt runner not showing prompt template until taking some action (v0.9.6)

### ISSUE THREAD

**Issue by chrisraygill** [firebase/genkit#1455]
**Describe the bug**

When opening a prompt in the prompt runner, the prompt template is not immediately shown unless I take some action such as filling in the input or click through the tabs on the right column.

Bug found in Genkit CLI version 0.9.6.

This is how my prompt looks when I open it up at first:

![image](https://github.com/user-attachments/assets/3a88b878-a78a-45b4-9f99-ca920b11bf30)

Then after taking some action:

![image](https://github.com/user-attachments/assets/2cf2437c-46ae-47bb-9ae6-088022d94bcf)

**Comment by tonybaroneee** [comment]
Fixed in https://github.com/FirebasePrivate/genkit-ui/pull/1172.
