### ISSUE TITLE
[Tooling] Model responses are much slower than they should be in Model and Prompt Runners

### ISSUE THREAD

**Issue by chrisraygill** [firebase/genkit#1456]
Model responses are much slower than they should be in Model and Prompt Runners.

Bug in Genkit Tools version: 0.9.6

Here is a video demonstrating the experience:

https://github.com/user-attachments/assets/1e2ff334-fc99-4430-8d48-7bf4edabafa9

In summary, running a simple prompt in my code against Gemini 1.5 Flash takes a second or less to respond.

Running the exact same prompt in the DevUI against Gemini 1.5 Flash takes much longer, and sometimes never resolves.

## Update

Might be related to https://github.com/firebase/genkit/issues/1455.

Looks like the response is being generated, but not shown until I take some sort of action like changing or setting the configurations.

https://github.com/user-attachments/assets/96d7eb92-9f13-4dbb-a96c-d19b0e6ed9ca

**Comment by tonybaroneee** [comment]
Fixed in https://github.com/FirebasePrivate/genkit-ui/pull/1172.
