### ISSUE TITLE
[JS] The functional version of `definePrompt` is not well supported by tooling 

### ISSUE THREAD

**Issue by chrisraygill** [firebase/genkit#1461]
DevUI completely ignores prompt model, model config, and structured output from `definePrompt`

Possibly related to: https://github.com/firebase/genkit/issues/1462

**Tooling version:** 0.9.7

**To Reproduce**
1. Use the following sample code
```ts
import { genkit, z } from 'genkit';
import { googleAI, gemini15Pro } from '@genkit-ai/googleai'

const ai = genkit({
  plugins: [googleAI()],
});

const codePrompt = ai.definePrompt(
  {
    name: 'codePrompt',
    model: gemini15Pro.withConfig({
      temperature: 0.6
    }),
    output: {
      schema: z.object({
        message: z.string().describe('Message to the user'),
        name: z.string().describe('Name of the person')
      })
    },
    input: {
      schema: z.object({
        name: z.string().describe('Name of the person')
      })
    },
    config: {
      temperature: 0.2
    }
  },
  async (input) => {
    return {
      messages: [{ role: 'user', content: [{ text: `Say hello to ${input.name}` }] }]
    };
  }
);

async function runCodePrompt() {
  const { output: codePromptOutput } = await codePrompt({ name: "Chris" });
  console.log("Code prompt:", codePromptOutput);
};

runCodePrompt();
```

2. Run the code locally, and see that it works as expected with the following output
```
Code prompt: { message: 'Hello, Chris', name: 'Chris' }
```

3. Open "codePrompt" in the DevUI prompt runner.

4. Notice that the model and config don't match up to the `definePrompt` code
![image](https://github.com/user-attachments/assets/15a8a50d-7b3b-41d7-b3d3-6b7bfad4cfb9)

5. Run the prompt with the same input as in the code - "Chris". Notice that the output does not conform the the structure specified in the code:
![image](https://github.com/user-attachments/assets/af4f668a-c84f-4dd6-97b3-976c2fc5025c)

6. View the trace and notice that it is consistent with the Prompt runner, not the code (ignored config and structured output).

![image](https://github.com/user-attachments/assets/913e6ba2-7031-4e41-8948-85354de10d03)

**Expected behavior**
When opening "codePrompt" in the DevUI prompt runner, it should respect the model and config defined in the code. Additionally, it should respect the structured output shape - or at least not ignore it.

See video for full walkthrough:

https://github.com/user-attachments/assets/c03c392f-e55e-4871-a729-93c6d2cd672e

**Comment by MichaelDoyle** [comment]
This appears to be because definePrompt does not set any of the prompt metadata in the registry as expected.

```json
"/prompt/codePrompt": {
    "key": "/prompt/codePrompt",
    "name": "codePrompt1461",
    "metadata": {
      "prompt": {},
      "type": "prompt"
    },
    "inputSchema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Name of the person"
        }
      },
      "required": [
        "name"
      ],
      "additionalProperties": true,
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  ```

**Comment by MichaelDoyle** [comment]
Opened https://github.com/firebase/genkit/pull/1484 to add the metadata.

Additional work will probably be required to make function-based prompts play nice with the dev-ui.

**Comment by MichaelDoyle** [comment]
Now that we have stop-gaps in place, closing in favor of #1533.
