### ISSUE TITLE
[JS] Prompt 'rendering' action does not enforce json output when output schema is provided

### ISSUE THREAD

**Issue by chrisraygill** [firebase/genkit#1462]
**Tooling version:** 0.9.7

Possibly related to https://github.com/firebase/genkit/issues/1461.

**Describe the bug**
DevUI prompt runner ignores structured output from `.prompt` file. Although, oddly, the structured output schema is reflected in the model input trace.

Running the `.prompt` file in my code produces the expected structured output shape, but running it in the Prompt runner does not.

There seems to be a disconnect between what's shown in the DevUI model input trace when running a `.prompt` file in the Prompt runner and what's actually being passed to the model.

**To Reproduce**
1. Use the following prompt and code sample:
```
---
model: googleai/gemini-1.5-flash
input:
  schema:
    name: string, "Name of the person"
output:
  schema:
    message: string, "Message to the user."
    name: string, "Name of the person."
config:
  temperature: 0.2
---

{{ role "user" }}
Say hello to {{name}}.
```
```ts
import { genkit, z } from 'genkit';
import { googleAI } from '@genkit-ai/googleai'

const ai = genkit({
  plugins: [googleAI()],
});

async function runPromptFile() {
  const promptFile = ai.prompt("prompt_file");
  const { output: promptFileOutput } = await promptFile({ name: "Pavel" });
  console.log("Prompt file: ", promptFileOutput);
};

runPromptFile();
```

See complete project code here: 

2. Run the code and see the following output as expected:
```
Prompt file:  { message: 'Hello, Pavel!', name: 'Pavel' }
```

3. Open the prompt in the DevUI prompt runner and run it with the same input as from the code -- "Pavel". Notice that the output does not following the expected output structure.

![image](https://github.com/user-attachments/assets/fa394781-9a0c-4a9b-949a-75be5de29278)

4. Check the trace. Notice that the output schema is being shown in the input trace, but for some reason doesn't seem to be used by the model.

![image](https://github.com/user-attachments/assets/7ef1dcb5-b022-4435-b218-4d37f13c2c87)

5. See complete trace here:
```
{
  "traceId": "1aaca66649bcd8017b520c502cd59a3c",
  "displayName": "googleai/gemini-1.5-flash",
  "startTime": 1733506575865,
  "endTime": 1733506576315.0583,
  "spans": {
    "7a4457a753f6d9d1": {
      "spanId": "7a4457a753f6d9d1",
      "traceId": "1aaca66649bcd8017b520c502cd59a3c",
      "startTime": 1733506575865,
      "endTime": 1733506576315.0583,
      "attributes": {
        "genkit:type": "action",
        "genkit:name": "googleai/gemini-1.5-flash",
        "genkit:isRoot": true,
        "genkit:path": "/{googleai/gemini-1.5-flash,t:action}",
        "genkit:input": "{\"messages\":[{\"role\":\"user\",\"content\":[{\"text\":\"Say hello to Pavel.\"}]}],\"config\":{\"temperature\":0.2,\"topK\":32,\"topP\":0.95},\"tools\":[],\"output\":{\"schema\":{\"type\":\"object\",\"properties\":{\"message\":{\"type\":\"string\",\"description\":\"\\\"Message to the user.\\\"\"},\"name\":{\"type\":\"string\",\"description\":\"\\\"Name of the person.\\\"\"}},\"required\":[\"message\",\"name\"],\"additionalProperties\":false}}}",
        "genkit:metadata:subtype": "model",
        "genkit:output": "{\"candidates\":[{\"index\":0,\"message\":{\"role\":\"model\",\"content\":[{\"text\":\"Hello, Pavel!\\n\"}]},\"finishReason\":\"stop\",\"custom\":{}}],\"custom\":{\"candidates\":[{\"content\":{\"parts\":[{\"text\":\"Hello, Pavel!\\n\"}],\"role\":\"model\"},\"finishReason\":\"STOP\",\"avgLogprobs\":-0.08503783345222474}],\"usageMetadata\":{\"promptTokenCount\":6,\"candidatesTokenCount\":5,\"totalTokenCount\":11},\"modelVersion\":\"gemini-1.5-flash\"},\"usage\":{\"inputCharacters\":19,\"inputImages\":0,\"inputVideos\":0,\"inputAudioFiles\":0,\"outputCharacters\":14,\"outputImages\":0,\"outputVideos\":0,\"outputAudioFiles\":0,\"inputTokens\":6,\"outputTokens\":5,\"totalTokens\":11},\"latencyMs\":449.7375410000095}",
        "genkit:state": "success"
      },
      "displayName": "googleai/gemini-1.5-flash",
      "links": [],
      "instrumentationLibrary": {
        "name": "genkit-tracer",
        "version": "v1"
      },
      "spanKind": "INTERNAL",
      "sameProcessAsParentSpan": {
        "value": true
      },
      "status": {
        "code": 0
      },
      "timeEvents": {
        "timeEvent": []
      }
    }
  }
}
```

**Expected behavior**
DevUI prompt runner shows the same output structure as when running the prompt in code.

**Video walkthrough**
https://github.com/user-attachments/assets/ce11775b-7190-4017-b78a-a1c11695fb42

**Comment by MichaelDoyle** [comment]
This appears to be, because the prompt 'rendering' action is not inferring "json" output format, based on the presence of the output schema in the same way that the rest of the framework does.

**Comment by MichaelDoyle** [comment]
The issue here was that the prompt runner is not inferring JSON mode from the presence of an output schema.

We'll fix this on the dev ui side, but the long term fix is to remove this code duplication, and enable the dev ui to call the "generate" helper via reflection.
