### ISSUE TITLE
[JS] DotPrompt.generate does not maintain input string encoding

### ISSUE THREAD

**Issue by FriedrichWessel** [firebase/genkit#1480]
**Describe the bug**
```javascript
formatPrompt.generate({
            input : {
                data: "Some \"string\" with special characters"
            },
            output : {schema: outputSchema}
        })
```

Replaces inner quotes with ascii encoding - instead of maintaining the correct encoding.
`Some \"string\" with special characters `
is converted into: 
`Some &quot;string&quot; with special characters `

**To Reproduce**
1. Use a simple prompt that has one input param as string
2. Provide a string that contains special characters ( like ", or ` ) 
3. Run the prompt 
4.  See that the input is send with ascii encoding to the AI - Model 

**Expected behavior**
The expected behaviour is that .generate would maintain the original encoding

**Runtime (please complete the following information):**
 - OS: MacOS
 - Version [14.2.1]

**Node version**
 v22.1.0

**Additional context**
Example Prompt

```yaml
---
model: openai/gpt-4o
config:
  temperature: 0.1
input:
  schema:
    story: string
---
Summarize the following story: 

{{story}}
```

Example Input : 
```json
{
    "story": "This is my \"Story\" about some stuff from other`s!"
}
```

Actual output send to the AI: 
`This is my &quot;Story&quot; about some stuff from other&#x60;s!`

Expected: 
`This is my "Story" about some stuff from other`s!`

**Comment by mbleigh** [comment]
Dotprompt uses Handlebars which HTML escapes variables by default. You should be able to send unescaped values using triple stache syntax:

```handlebars
{{{story}}}
```

See: https://handlebarsjs.com/guide/expressions.html#html-escaping

We should probably add this to the docs.

**Comment by NimJay** [comment]
@mbleigh, what are your thoughts on defaulting (always using) triple brackets (`{{{`)?
I assume no models expect strings to be HTML-escaped so this should be a safe default.

**Comment by mbleigh** [comment]
I've been considering turning on `{noEscape: true}` in Handlebars to address this, but I've been worried it could be considered a breaking change. I haven't entirely decided whether I consider it a bugfix or a breaking change, because the .prompt format really doesn't need to be escaping HTML but changing the default behavior could be bad if people are depending on it.
