### ISSUE TITLE
[Dev UI] Modify hover state of table rows

### ISSUE THREAD

**Issue by mjchristy** [firebase/genkit#1507]
Please change the table hover color to 25% of the nav highlight color.

Dark mode: 
RGBA: 57, 64, 80, 25
Light mode: 
RGBA: 190, 198, 220, 25

And remove the cursor:pointer for the evals view table since it's not a clickable row.

**Comment by hugomurillomtz** [comment]
Fixed with: https://github.com/FirebasePrivate/genkit-ui/pull/1219
