### ISSUE TITLE
[Dev UI] Evals model config popover does not render correctly on small screens

### ISSUE THREAD

**Issue by MichaelDoyle** [firebase/genkit#1555]
## Overview

The model config popover does not render properly if there is not enough space on the right hand side.

<img width="1003" alt="Image" src="https://github.com/user-attachments/assets/5944aa7c-a05b-4f55-8d1a-738b08850026" />

Additionally, the frontmatter does not appear to render properly, in the general case (extra whitespace before the first `---`)

<img width="404" alt="Image" src="https://github.com/user-attachments/assets/962d9399-9001-4765-b25e-c96490e0ff9f" />

### User goal(s)
View the model config.

## Requirements

1. Ideally, we'd render the popover to the bottom-left in this situation
2. Fix the rendering of the frontmatter (in _all_ scenarios)

### Acceptance Criteria
1. User can see the model config
2. Frontmatter is rendered correctly

### Designs

N/A

## Notes

N/A

**Comment by hugomurillomtz** [comment]
Fixed with: https://github.com/FirebasePrivate/genkit-ui/pull/1228
