### ISSUE TITLE
Add audio (and maybe also video) support to the Genkit UI

### ISSUE THREAD

**Issue by Dabolus** [firebase/genkit#185]
**Is your feature request related to a problem? Please describe.**
Multimodal LLMs are coming and most of them will support for sure support audio input/output (see GPT-4o). Video input/output is probably coming next.

**Describe the solution you'd like**
Right now the UI has support for both image input and output. I think it would be trivial to also add support for audio and video, since native HTML components can be leveraged without the need of custom components.

**Describe alternatives you've considered**
For a model I'm working on, I'm converting the audio input in base64 and providing it as string. Then, I'm getting the output base64 string and converting it back to a file to listen to the result. This approach, but it's very time consuming.

**Additional context**
This is the approach I'm currently using. As you can imagine, this is not ideal.

![image](https://github.com/firebase/genkit/assets/28671340/61e19420-8d1c-42e1-bf71-a41b7fdc809e)

For images instead, there is native support for both input and output.

![image](https://github.com/firebase/genkit/assets/28671340/a2f34376-410e-42cd-adae-2e2a51d47320)

![image](https://github.com/firebase/genkit/assets/28671340/1955e3fb-1daa-476a-be04-8fc29acf8ede)

**Comment by chrisraygill** [comment]
Audio and video for the model runner are both supported for media input in Genkit 0.9.7!
