### ISSUE TITLE
[FR] Improve Passing in the Auth Object in the DevUI

### ISSUE THREAD

**Issue by i2amsam** [firebase/genkit#188]
Cross-filing from @peterfriese 

**Is your feature request related to a problem? Please describe.**
When running an onFlow from the DevUI it's really easy to forget to provide an auth object, and then I have to go in an type one in.

**Describe the solution you'd like**
Would it be feasible to provide some sort of dummy auth JSON out of the box, to make this easier?

Ideally it would "just work" from the DevUi to hit run.

**Describe alternatives you've considered**

**Additional context**

**Comment by i2amsam** [comment]
This got improved some by @sam-gc's enhancement to hide the auth box when there's no auth involved

**Comment by tonybaroneee** [comment]
Fixed w/ https://github.com/FirebasePrivate/genkit-ui/commit/f9a4d56f48fd613055930f43cd7cc9dc17e9f676.
