### ISSUE TITLE
[Tooling] Prompt playground doesn't resolve tools for Dotprompt

### ISSUE THREAD

**Issue by mbleigh** [firebase/genkit#197]
**Describe the bug**
When using Dotprompt with tools, the prompt playground doesn't properly resolve them.

**To Reproduce**
1. Define a tool using `defineTool`
2. Activate the Dotprompt plugin
3. Write a `.prompt` that includes `tools: nameOfTool`
4. Open Genkit UI and try to run the prompt

**Expected behavior**
The prompt executes including tool calling.

**Actual behavior**  
The prompt errors with:

```
Error: INVALID_ARGUMENT: Schema validation failed. Parse Errors:

- tools.0: must be object
```

**Comment by MichaelDoyle** [comment]
We're hashing out the tool-call rendering capabilities in the model playground (early this week), and then will integrate into the prompt runner as well. We could push a quick fix to unblock this particular error if needed.

**Comment by mbleigh** [comment]
No urgency, just reporting the bug.

**Comment by MichaelDoyle** [comment]
Fix is in for the next update.

**Comment by i2amsam** [comment]
Fixed!
