### ISSUE TITLE
[FR] Add a "clear all" button to the model playground

### ISSUE THREAD

**Issue by MichaelDoyle** [firebase/genkit#199]
**Is your feature request related to a problem? Please describe.**
Often times you want to reset the context. Right now you need to click delete on every message to do so.

**Describe the solution you'd like**
A single button to clear the message list.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by tonybaroneee** [comment]
Added. Will be available in the next release of Genkit.

**Comment by tonybaroneee** [comment]
Added! Will be available in the next release of Genkit.
