### ISSUE TITLE
[JS] @genkit-ai/vertexai plugin current version on NPM does not support gemini 1.5 flash, despite PR #167

### ISSUE THREAD

**Issue by Jacquesjh** [firebase/genkit#219]
**Describe the bug**
The current version 0.5.0 of the plugin on npm  was released one day before the addition of gemini 1.5 flash, which was on may 14.
Ever since the anouncement last week i am dying to try out the new model.
Seems odd that it was added but the new version of the plugin was not released.

**Comment by pavelgj** [comment]
0.5.1 has just been released with Gemini 1.5 Pro Flash support.
