### ISSUE TITLE
[Tooling] The prompt playground does not shows the output when it is a JSON format

### ISSUE THREAD

**Issue by Jacquesjh** [firebase/genkit#221]
**Describe the bug**
When experimenting in the prompt playground, the model response will not appear if the output is a JSON. The only way to see the output is viewing it's trace.
When the output is text it works fine.

**Screenshots**
![image](https://github.com/firebase/genkit/assets/61204659/95f4758d-2122-45b9-8d31-a3568122a5ed)
![image](https://github.com/firebase/genkit/assets/61204659/073f50a6-94c8-4d7e-9288-66e794b1be80)

**Comment by MichaelDoyle** [comment]
Would it be possible to provide a representative output from the model and/or trace?

**Comment by shrutip90** [comment]
I tried to test this out. One of our samples (js/testapps/flow-simple-ai) has a prompt with json output. It seems to be displaying the output in the prompt playground fine:

![image](https://github.com/user-attachments/assets/53de705a-77f0-4244-89c7-b81267ed5fe7)

I am going to close this one for now as there was no information provided by the user. Please reopen if you have a specific use case with the issue and provide more details about it. Thanks!

**Comment by MichaelDoyle** [comment]
@shrutip90 Maybe one thing to double check; in the screenshot the schema is not an object, but an array. Does that have any impact?

**Comment by shrutip90** [comment]
> @shrutip90 Maybe one thing to double check; in the screenshot the schema is not an object, but an array. Does that have any impact?

Thanks @MichaelDoyle. Tested that out too. I changed the sample to output an array of reasonings:
---
model: vertexai/gemini-1.0-pro
input:
  schema:
    question: string
output:
  format: json
  schema:
    answer: string, the answer to the question
    id: string, the selected id of the saying
    reasoning(array): string, why the saying applies to the question
---

and it still works:
![image](https://github.com/user-attachments/assets/13254b97-e768-4815-9e93-b2757be50a18)
