### ISSUE TITLE
[Go] spawn Unknown system error -126 when running `genkit start`

### ISSUE THREAD

**Issue by ssbushi** [firebase/genkit#282]
**Describe the bug**
When trying to start the Dev UI using `genkit start` in a go sample app, the following error is thrown:

```
node:internal/child_process:421
    throw errnoException(err, 'spawn');
    ^

Error: spawn Unknown system error -126
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at spawn (node:child_process:761:9)
    at Object.<anonymous> (/usr/local/google/home/ssbushi/OpenSource/genkit/go/samples/rag/sp.js:6:15)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  errno: -126,
  code: 'Unknown system error -126',
  syscall: 'spawn'
}
```

**To Reproduce**
Note: This reproduction step may not work based on your PATH env var.

1. Run `genkit start` in a go genkit app.

**Expected behavior**
The Dev UI starts up normally.

**Runtime (please complete the following information):**
 - OS: Linux Debian

**Go version**
go version go1.23-20240419-RC02 cl/626470163 +7f76c00fc5 X:fieldtrack,boringcrypto linux/amd64

**Workaround**

I was running into this issue even though `go` is included in my PATH variable. 

```
$ which go
# returns path/to/golang/bin/go
$ echo $PATH
# ....:path/to/golang/bin/:....
```
My workaround for this issue is to append Go's path at the front of the my PATH variable

```
export PATH=path/to/golang/bin/:$PATH
```

**Comment by jba** [comment]
So one weird thing is that PATH should hold directories, not binaries. If your `go` binary is at /usr/bin/go, then your PATH should have /usr/bin.

**Comment by ssbushi** [comment]
Sorry, you're right. I meant to show directories in the example above. Edited now.

**Comment by i14h** [comment]
@ssbushi is this already fixed?

**Comment by ssbushi** [comment]
The workaround I mentioned above fixed this for me. I haven't looked into this further
