### ISSUE TITLE
Add support for JSON mode and JSON schema conformance to Gemini models

### ISSUE THREAD

**Issue by mbleigh** [firebase/genkit#290]
- Gemini 1.5 Flash supports "JSON mode" where it will guarantee JSON output.
- Gemini 1.5 Pro supports both JSON mode and "JSON schema mode" where it will actually do schema conformance for us

These are great features and we should add them for both Google AI and Vertex plugins. [Docs here](https://ai.google.dev/gemini-api/docs/api-overview#json).

**Comment by njpearman** [comment]
Hi @mbleigh, I'm really keen on JSON mode being available for Gemini in genkit.

Is there a timeline for getting JSON mode into the `googleAI` plug-in for Gemini 1.5 yet? Could I help get it in place if it isn't on anyone else's radar? (Just to say up-front I've yet to look at JSON Schema mode in detail so I might prefer to look at JSON mode on its own before JSON schema mode.)

**Comment by mbleigh** [comment]
Thanks for the bump @njpearman! I don't think anyone is actively working on this yet although I'd hope it will come off the backlog soon. If you want to take a stab at a PR I'd be happy to review.

**Comment by njpearman** [comment]
Great. I'll do the contrib reqs then try to get something together so we can discuss particulars on the PR.
