### ISSUE TITLE
When calling retriever from the dev UI it returns query as the first document

### ISSUE THREAD

**Issue by pavelgj** [firebase/genkit#34]
Called from the dev UI:

![image](https://github.com/firebase/genkit/assets/774654/45c870dd-3c39-4621-8271-c4cf5904439a)

This doesn't happen when calling the retriever as part of a flow:

![image](https://github.com/firebase/genkit/assets/774654/0653aad4-ce6d-4524-844c-55cbc1d3bdaf)

**Comment by ssbushi** [comment]
I cannot reproduce this bug:

![image](https://github.com/firebase/genkit/assets/66321939/7df5e4e7-45c9-4ff7-a992-3bdd49ef884d)

**Comment by MichaelDoyle** [comment]
Unable to reproduce. We can re-open if it comes up again.
