### ISSUE TITLE
[Go] `genkit start` does not properly shut down previous runner process before starting new one

### ISSUE THREAD

**Issue by pavelgj** [firebase/genkit#395]
**Describe the bug**
```
Detected a change in main.go. Waiting for other changes before reloading.
Reloading app code.
App process exited with code null
Starting app at `.`...
Warn: Port 3100 not available, using 3101 instead.
time=2024-06-12T10:17:19.460-04:00 level=INFO msg="starting dev server"
time=2024-06-12T10:17:19.461-04:00 level=INFO msg="starting flow server"
time=2024-06-12T10:17:19.461-04:00 level=INFO msg=listening addr=:3400
time=2024-06-12T10:17:19.461-04:00 level=INFO msg=listening addr=:3101
time=2024-06-12T10:17:19.461-04:00 level=INFO msg="listen tcp :3400: bind: address already in use"
exit status 1
App process exited with code 1
```

**To Reproduce**
reproducible on `coffee-shop`

**Comment by happy1999** [comment]
Hi, it is one year later now @2025-May, but this same bug still exists. Team, there is already 10x competitors here already and your CEO just had an interview talking about the AI competitiveness of Google. God

**Comment by sud33p** [comment]
Hi, it is one year and 4 months later now @2025-October, but this same bug still exists. The docs and examples are hard to find and after wasting so much time on this, I am still confused about this error and what port to use. Good job. I should look into now what I think the other 15x competitors.

**Comment by pavelgj** [comment]
> Hi, it is one year and 4 months later now @2025-October, but this same bug still exists. The docs and examples are hard to find and after wasting so much time on this, I am still confused about this error and what port to use. Good job. I should look into now what I think the other 15x competitors.

what version of genkit cli are you running? (`genkit --version`)
