### ISSUE TITLE
[JS] Refactor "generate" into a pseudo-flow

### ISSUE THREAD

**Issue by mbleigh** [firebase/genkit#408]
Right now `generate` lives in a liminal space between being some code wrapped around a model action and being a heavier "built-in flow" that handles things like tool loops and eventually retries etc.

I think the latter is more the direction we should take. Ideally `generate` would be a built-in flow/action such that in a trace you can see:

1. Each iteration of a tool/reasoning loop as a separate LLM call in the trace
2. Things like retries and output healing as separate steps as well

The `generate` methods then become syntactical wrappers around the `generate` action, transforming the inputs into a serializable form.

**Comment by i14h** [comment]
@mbleigh I assigned it to yourself to bring it up in a discussion in Discord, and later if turned into an action item we can assign it to someone else

**Comment by chrisraygill** [comment]
Done

**Comment by apascal07** [comment]
Is this actually done? Where? @chrisraygill
