### ISSUE TITLE
Deprecate Gemini 1.0 Pro Vision

### ISSUE THREAD

**Issue by thatfiredev** [firebase/genkit#413]
According to https://ai.google.dev/gemini-api/docs/models/gemini#model-variations the [Gemini 1.0 Pro Vision](https://github.com/firebase/genkit/blob/f594e1fe06d8ed3cb3bfbca41df822c7b39ca7e4/js/plugins/googleai/src/gemini.ts#L90) model is deprecated.

Is there a way of deprecating models in Genkit ?

**Comment by pr-Mais** [comment]
Could do it in 2 ways:
- Add a JSDoc `@deprecated` flag.
- Also show a warning in the console when the model is called (I think this can be added as a middleware internally?).
