### ISSUE TITLE
[JS] Tracing missing "root" span for nextjs

### ISSUE THREAD

**Issue by i2amsam** [firebase/genkit#434]
**Describe the bug**
When prod traces are logged with `autoInstrumentation=true` some traces fail to be shown in the DevUI.  The proximate cause is that traces are logged without a startTime attribute on the span.  You will also see spans in GCP with "Missing span ID" errors. The start/end dates are missing for the same reason. We determined that turning off autoinstrumentation restores startTime, because the root span will be provided by Genkit in that case.

Upon further investigation, this appears to be attributed to Nextjs specific behavior. Sentry also encountered this issue: https://github.com/getsentry/sentry-javascript/issues/11046. Most likely Nextjs specific implementation details are required to resolve. Nextjs provides a "hook" (`instrumentation.ts`) for initializing OTel. See also: https://nextjs.org/docs/app/api-reference/file-conventions/instrumentation.

**To Reproduce**
Steps to reproduce the behavior. Code samples.

**Expected behavior**
All prod traces in the remote tracestore should be viewable in the DevUI

**Screenshots**
Here's an example trace in Firestore without startTime

<img width="933" alt="image" src="https://github.com/firebase/genkit/assets/665326/b1602ced-f796-46c3-a635-16baaf196669">

And in cloud trace (missing root span)
<img width="415" alt="image" src="https://github.com/firebase/genkit/assets/2858322/f809df66-854e-435d-b9b6-65008975a08f">

**Runtime (please complete the following information):**
NextJS app deployed to Firebase App Hosting

**Comment by MichaelDoyle** [comment]
Fixed via https://github.com/firebase/genkit/pull/892
