### ISSUE TITLE
[JS] Add support for Vertex Vector Search to the Vertex AI plugin

### ISSUE THREAD

**Issue by chrisraygill** [firebase/genkit#448]
**Is your feature request related to a problem? Please describe.**

Developers who want to use Vertex Vector Search as a scalable, production-ready solution don't have a way to do so through Genkit.

**Describe the solution you'd like**

Make Vertex Vector Search available through the Vertex AI plugin as indexer and retriever components.

**Describe alternatives you've considered**

Developers can define their own indexer and retriever components, but it's more convenient to have it exposed through the plugin as a first class experience.

**Additional context**

More info on Vertex Vector Search available here: https://cloud.google.com/vertex-ai/docs/vector-search/overview

**Comment by cabljac** [comment]
@chrisraygill I thought I'd discuss this here, let me know if it should be somewhere else:

Unless I've misunderstood. a Vertex AI index will store an `id` and the `embedding`, and users are expected to keep the content of the document and any metadata which corresponds to this id somewhere else (In another database, e.g BQ, to retrieve via the id)

[see here for example](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/vector_search/sdk_vector_search_create_stack_overflow_embeddings_vertex.ipynb)

In Genkit we have a Document which has content and metadata, and a retriever responds with a list of documents.

Should we enforce BigQuery as the database in this feature?

**Comment by cabljac** [comment]
adding for reference https://github.com/firebase/genkit/pull/519
