### ISSUE TITLE
consider changing `geminiPro` variable to be more clear that it's specifically for Gemini 1.0 Pro (and not for Gemini 1.5 Pro)

### ISSUE THREAD

**Issue by rachelsaunders** [firebase/genkit#462]
IMO - For Google AI and Vertex AI plugins, the variable naming strategy is a bit strange for "Gemini Pro".  It's `geminiPro`.

Google AI:
- https://github.com/firebase/genkit/blob/main/js/plugins/googleai/src/gemini.ts#L75
- https://firebase.google.com/docs/genkit/plugins/google-genai#usage

Vertex AI:
- https://github.com/firebase/genkit/blob/main/js/plugins/vertexai/src/gemini.ts#L60
- https://firebase.google.com/docs/genkit/plugins/vertex-ai#generative_ai_models

Is this referring to Gemini 1.0 Pro or Gemini 1.5 Pro?  From digging into the source code, I can see that it's referring to Gemini 1.0 Pro, but it's not immediately obvious from the samples / snippets.

It looks like when Gemini 1.5 models were added to the plugins, the strategy of including the generation value started up, but right now IMO it's confusing to still have `geminiPro` available (especially since right now it's used in all the snippets and samples).

Note that the new naming strategy of eliminating the period (i.e., `gemini15pro`) could be problematic since it looks like that's referencing Gemini 15 Pro, not Gemini 1.5 Pro.  If we ever move to full number generation versioning scheme (vs decimal increments), this naming strategy will break down.

**Comment by mbleigh** [comment]
I think we should probably deprecate `geminiPro` and add `gemini10Pro`. Agree that the decimal issue is unfortunate but I'm genuinely not sure how to solve it other than something like `gemini1_5Pro` which is even worse.

If we take a convention of *always* including a single decimal then we're going to be okay unless they release Gemini 1.75 😄
