### ISSUE TITLE
Hide cursor when intro animation has finished

### ISSUE THREAD

**Issue by peterfriese** [firebase/genkit#50]
After the Genkit intro animation has finished, the cursor is still visible:

![CleanShot 2024-05-07 at 13 50 23@2x](https://github.com/firebase/genkit/assets/232107/c7ebacfa-fde4-49cf-997e-525df0bad714)

I think it'd look better if the cursor disappeared once the animation has finished.

**Comment by tonybaroneee** [comment]
Thanks for the feedback, Peter. This is intentionally there for the text editor cursor blink effect, so I'm going to leave it in for now.
