### ISSUE TITLE
Streaming Callback: awaiting .output() if not providing a format

### ISSUE THREAD

**Issue by cabljac** [firebase/genkit#52]
I was using the generate method.

As far as I understand, we know that a stream has finished when `.output()` resolves. However when you don't provide an `output` parameter (as i just want to use `.text()` in the streaming callback) it seems like `.output()` will reject:
```bash
>  [ERROR]  bolt-app UnknownError: No JSON object or array found in model output: (....the llm text response here, which is what i wanted)```

**Comment by chrisraygill** [comment]
@pavelgj status?

**Comment by pavelgj** [comment]
@cabljac do you have a repro?
