### ISSUE TITLE
[Tooling] The genkit init spinner doesn't spin when installing npm packages

### ISSUE THREAD

**Issue by mjchristy** [firebase/genkit#531]
**Describe the bug**
The npm installer icon spinner doesn't spin when running genkit init

**To Reproduce**
1. Run genkit init

**Expected behavior**
It should spin to show that it is working

**Screenshots**
![installing npm](https://github.com/firebase/genkit/assets/3275566/86bc2a24-b9b1-4b0d-9afc-cd4df057c2c3)

**Comment by cabljac** [comment]
https://github.com/sindresorhus/ora#why-does-the-spinner-freeze

The problem here is that js is single-threaded and the sync processes are stopping the spinner from advancing.

Investigating to see how we can resolve this
