### ISSUE TITLE
Support Vertex AI Gemini grounding with Google Search and Vertex data stores

### ISSUE THREAD

**Issue by chrisraygill** [firebase/genkit#547]
**Is your feature request related to a problem? Please describe.**

Vertex AI offers the ability to [ground responses for Gemini models](https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/ground-gemini) using Google Search or your own data in within Vertex AI Search datas stores.

It appears to supported in the Python and [Node.js SDK](https://cloud.google.com/vertex-ai/generative-ai/docs/reference/nodejs/latest#grounding-using-vertex-ai-search-preview), but not yet in the Go SDK. 

In the Vertex AI Gemini API, it works by passing in the grounding mechanism as a tool to the model, like so (Node.js):

```JavaScript
async function generateContentWithVertexAISearchGrounding() {
  const generativeModelPreview = vertexAI.preview.getGenerativeModel({
    model: textModel,
    // The following parameters are optional
    // They can also be passed to individual content generation requests
    safetySettings: [{category: HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT, threshold: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE}],
    generationConfig: {maxOutputTokens: 256},
  });

  const vertexAIRetrievalTool = {
    retrieval: {
      vertexAiSearch: {
        datastore: 'projects/.../locations/.../collections/.../dataStores/...',
      },
      disableAttribution: false,
    },
  };
  const result = await generativeModelPreview.generateContent({
    contents: [{role: 'user', parts: [{text: 'Why is the sky blue?'}]}],
    tools: [vertexAIRetrievalTool],
  })
  const response = result.response;
  const groundingMetadata = response.candidates[0].groundingMetadata;
  console.log("Grounding metadata is: ", JSON.stringify(groundingMetadata));
}
generateContentWithVertexAISearchGrounding();
```

I'm not sure how this would work with Genkit's current design for specifying tools in a generation request.

**Comment by pr-Mais** [comment]
Perhaps adding a flag `enableGoogleSearchGrounding=true` to the model would be a straightforward DX.

**Comment by chrisraygill** [comment]
@pavelgj from a design perspective, any thoughts on how we might do this?

Maybe just making them custom configuration parameters for the Vertex Gemini models rather than tools? Not sure if that would have odd downstream effects when it comes to tool handling stuff like forced function calling.

**Comment by chrisraygill** [comment]
@pr-Mais any proposals from you on how this might look?
