### ISSUE TITLE
Create code to introduce developers to using genkit

### ISSUE THREAD

**Issue by MaesterChestnut** [firebase/genkit#56]
P0
- [x] Create menu/basic pulling from the existing menu section  https://github.com/firebase/genkit/pull/57
- [x] Replace genkit init output with "menuSuggestionFlow" & modify documentation for Getting Started https://github.com/firebase/genkit/pull/62
- [ ] Create menu/generation example https://github.com/firebase/genkit/pull/107
- [x] Create the menu/rag sample with a local db https://github.com/firebase/genkit/pull/82
P1
- [ ] Create a menu/firebase sample with auth, deployment, and firestore vector
- [ ] Create the menu/evaluation sample with genkit evaluators
P2
- [ ]  Create the menu/express sample
- [ ] Create the menu/telemetry sample
- [ ] Create the menu/multi-step sample
- [ ] Create gif for tour through Developer UI with menu sample

**Comment by i14h** [comment]
are we continuing developing these?

**Comment by MichaelDoyle** [comment]
I don't think so, but I will follow up with the original folks involved.

I think it would be better to look at the docs and sample code holistically.
