### ISSUE TITLE
[Tooling] Sometimes cannot cancel out of `genkit start` command

### ISSUE THREAD

**Issue by chrisraygill** [firebase/genkit#589]
**Describe the bug**

When I'm using VSCode's Integrated Terminal, I often cannot cancel out of a `genkit start` command. I get these `^C` characters instead. It doesn't happen outside of VSCode (e.g. iTerm). I'm using oh my zsh. It's only the genkit start command that this happens with

![image](https://github.com/firebase/genkit/assets/15097183/e54694e2-5bf9-4ab9-baf6-995187bd4123)

**Comment by Yorkemartin** [comment]
i get this issue in iTerm2 + zsh

**Comment by cabljac** [comment]
Does anyone get this issue without iTerm2 and zsh? I am using these as well

**Comment by cabljac** [comment]
<img width="476" alt="Screenshot 2024-07-30 at 08 23 12" src="https://github.com/user-attachments/assets/4a0dda35-ca9d-439b-92f0-b2d30b50acce">
managed to repro it unintentionally. I think it may be upon reload. I'm using zsh and iTerm2 still

**Comment by tonybaroneee** [comment]
<img width="1242" alt="image" src="https://github.com/user-attachments/assets/39a9cfc2-fbd7-4a9c-b9b4-65ae525c7195">

Repro'd as well. zsh + iTerm2.

**Comment by cabljac** [comment]
might be related to readline, which we're using

https://github.com/nodejs/node/issues/4758
