### ISSUE TITLE
[Tooling] Error in app process

### ISSUE THREAD

**Issue by dario-digregorio** [firebase/genkit#625]
**Describe the bug**
I just followed the nextJS example in the [docs](https://firebase.google.com/docs/genkit/nextjs) and get this error:
```
Error: Error in app process: spawn /usr/local/lib/node_modules/genkit/node_modules/@genkit-ai/tools-common/node_modules/.bin/tsx ENOENT
```

I have an repo which you can see the error.

**To Reproduce**
1. `git clone https://github.com/dario-digregorio/genkit-example`
2. `genkit start`

**Expected behavior**
Should start Genkit

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version node `v20.15.1`

**Comment by ariel-pettyjohn** [comment]
Same issue here when I run `genkit start` after initializing Genkit with a brand new Next.js project.

OS: `Windows 11 Home`
Node Version: `20.12.2`
NPM/NPX Version: `10.8.0`

**Comment by ariel-pettyjohn** [comment]
I'm not sure if this has any relation to my previous observation about the `...\tools-common\node-modules`, but if I delete the `genkit-tools.conf.js` that gets generated by `genkit init` then the above ENOENT error goes away.

Here are the contents of that file on my system:

`module.exports = {
  runner: {
    mode: 'harness',
    files: ['./src/app/*.ts'],
  },
};`

**Comment by cabljac** [comment]
The Next.js docs don't mention running `npm install` which is probably needed in some situations, e.g if you clone a repo and just try to run `genkit start` you'll likely run into a "module not found" error. I'll start a thread in the Genkit discord server about making the docs clearer there.

I haven't been able to reproduce the error by cloning the repo @dario-digregorio provided. I'll try with a new Next.js project.
