### ISSUE TITLE
[Docs] which models supports tools?

### ISSUE THREAD

**Issue by xster** [firebase/genkit#661]
Trying out a few ollama models. But they fail with 

`Model "ollama/qwen2" does not support tools, but some tools were supplied to generate(). Please call generate() without tools if you would like to use this model.`

Even phi3 or gemma2 doesn't support tools. Well which ones do support tools?

**Comment by MichaelDoyle** [comment]
Hey xster. Currently ollama does not support tool (function) calling. Models that do support it include:

- Google Gemini (either via Google AI or Vertex AI plugins)
- OpenAI and Anthropic (via their respective 3P plugins)
- Anthropic (via Vertex AI plugins) is coming via #573

Tool (or function) calling is generally dependent on availability from the model provider. It's my understanding that ollama does not provide a tool calling API. There _are_ frameworks that provide "wrappers" that implement tool calling for _any_ model so long as it can provide structured output (i.e. json).

This is something we could discuss and consider either internally (perhaps as a plugin?) or as a community plugin.

**Comment by xster** [comment]
Not supporting ollama is ok. It should just be documented. Either here https://firebase.google.com/docs/genkit#4_give_llms_tools or in a breakout page about tool use (though I notice tool doesn't have a page)

**Comment by xster** [comment]
Though it seems like langchain somehow supports tools via ollama

**Comment by MichaelDoyle** [comment]
I see. Yes, the docs for tool calling can _definitely_ be improved -- we'll prioritize that. I agree, on the page you linked to, things are worded in such a way that it appears that "tool calling" is a Genkit _provided_ feature, and not dependent on model specific capabilities. The Generate Content page does mention tool calling is a model specific feature: https://firebase.google.com/docs/genkit/models#tools_and_function_calling, but its not very helpful. 

I think it will be tough for us to list model by model what features are supported; model specific documentation is the source of truth for that. But maybe there is a way for us to make "supported features" more easily discoverable in the framework. You can see this pretty easily in the code if you know where to look. Here is ollama: https://github.com/firebase/genkit/blob/main/js/plugins/ollama/src/index.ts#L72-L75

Wrt langchain, yes, they are doing this via an abstraction/wrapper layer. We could consider the same, perhaps via middleware. I'll open a FR for this.

**Comment by xster** [comment]
Also see https://ollama.com/blog/tool-support

**Comment by MichaelDoyle** [comment]
Fixed via https://github.com/firebase/genkit/pull/809
