### ISSUE TITLE
[Go] ollama.DefineEmbedder support.

### ISSUE THREAD

**Issue by Slahser** [firebase/genkit#670]
**Describe the bug**
A clear and concise description of what the bug is. include full error messages.

In this menu example, is there a way to reporduce it using Ollama?

https://github.com/firebase/genkit/blob/main/go/samples/menu/main.go#L76

**To Reproduce**
Steps to reproduce the behavior. Code samples.

ollama.DefineEmbedder(ollama.ModelDefinition{Name: "nomic-embed-text"}, nil)

**Expected behavior**

**Screenshots**

**Runtime (please complete the following information):**
 - OS: [e.g. Linux, MacOS]

** Go version
 -  run `go version` at paste here

**Additional context**

**Comment by cabljac** [comment]
closing in favour of issue to track https://github.com/firebase/genkit/issues/728
