### ISSUE TITLE
[Go] [JS] add support for ollama embeddings

### ISSUE THREAD

**Issue by pavelgj** [firebase/genkit#728]
Currently ollama plugin only supports chat/generate models, however ollama supports embeddings models as well: https://ollama.com/blog/embedding-models

**Comment by cabljac** [comment]
related/dupe: https://github.com/firebase/genkit/issues/670

**Comment by cabljac** [comment]
See

https://github.com/firebase/genkit/pull/751

https://github.com/firebase/genkit/pull/807

**Comment by huangjeff5** [comment]
See https://github.com/firebase/genkit/pull/841

**Comment by pavelgj** [comment]
Looks like the embeddings support was rolled back (due to merge issue) by not reapplied?
@cabljac could you please make sure it's done in both main and next branches? Thanks.
