### ISSUE TITLE
[Dev UI] Reset button should respect initial model params set from trace

### ISSUE THREAD

**Issue by MichaelDoyle** [firebase/genkit#729]
**Describe the bug**
The "reset" button for the model config sets all values to the "default" values. However, when if the runner was loaded from a trace, we should _probably_ reset to the values pre-loaded by the trace instead.

**To Reproduce**
1. Go to the model runner, and tweak some configurations. Run a prompt.
2. Click view trace
3. Click "open in model runner..." (yes, you've made a loop 😝 )
4. Click reset (values from trace will be "lost")

**Expected behavior**
If a trace was loaded, essentially the config values from the trace should be respected as the "defaults". See addt'l context for caveat(s).

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Mobile (please complete the following information):**
N/A

**Additional context**
There is a gotcha here, which is that if the developer truly does want a "blank" Playground with reasonable defaults, how should they get to it? We could do two buttons ("Reset changes" and "Use defaults"). Or...something else?

FWIW, clicking the model again on the LHS _will_ reset to the defaults (i.e. clean playground).

cc @pavelgj @mjchristy @shrutip90

**Comment by tonybaroneee** [comment]
Fixed in https://github.com/FirebasePrivate/genkit-ui/pull/1091/commits/3848c7e96d004586757d320c1a9dccb5b7593561.
