### ISSUE TITLE
[Tooling] Prompt playground should preserve leading whitespace on lines

### ISSUE THREAD

**Issue by mbleigh** [firebase/genkit#741]
**Describe the bug**
In the prompt playground leading whitespace is not respected when displaying the rendered prompt.

Source:
![image](https://github.com/user-attachments/assets/74960b29-f1d2-4611-b4ec-410000e4d791)

In playground:
![image](https://github.com/user-attachments/assets/c7ff58f4-3088-48be-a22c-d992437875e3)

**Comment by MichaelDoyle** [comment]
Fixed in 0.6.0.
