### ISSUE TITLE
[Tooling] Prompts that return data don't display correctly in Dev UI

### ISSUE THREAD

**Issue by mbleigh** [firebase/genkit#748]
When using a model that returns `DataPart` instead of text, the prompt playground doesn't display anything:

![image](https://github.com/user-attachments/assets/5e7c8f4f-3d00-47fc-8922-6c8c2577e222)

**Comment by MichaelDoyle** [comment]
@mbleigh do you have a quick example (or model) we should look at?

**Comment by mbleigh** [comment]
Try literally any JSON-mode output in Gemini now. Now that Gemini natively supports JSON mode, the returned parts are `[{data: {...}]` instead of e.g. `[{text: "```json\n{...}\n```"]`

**Comment by MichaelDoyle** [comment]
I see.... right under my nose. :) I had no idea. Thanks!
