### ISSUE TITLE
[DevUI] flow auth is not passed to the backend if input is not provided

### ISSUE THREAD

**Issue by pavelgj** [firebase/genkit#753]
See this sample flow

```ts
defineFlow({name: "qa", authPolicy: () => {}}, async () => {
  const auth = getFlowAuth();
  console.log("auth", auth)
})
```

Note flow input is void/optional.

In the Dev UI if you specify the Auth object, but not the input (leave input blank -- valid for this flow) the auth will be ignored:

HTTP request from the dev UI
```
POST http://localhost:4000/api/runAction?batch=1

{"0":{"key":"/flow/qa","input":{"start":{}}}}
```

however if you specify something (anything) in the input the auth is passed in correctly:

```
POST http://localhost:4000/api/runAction?batch=1

{"0":{"key":"/flow/qa","input":{"start":{"input":"something"},"auth":{"user":"foo"}}}}
```

**Comment by shrutip90** [comment]
Fixed in https://github.com/FirebasePrivate/genkit-ui/pull/1004.
