### ISSUE TITLE
[DevUI] Flow playground does not render the correct sample JSON

### ISSUE THREAD

**Issue by pavelgj** [firebase/genkit#773]
Flow schema:

```json
{
  "type": "string",
  "$schema": "http://json-schema.org/draft-07/schema#"
}
```

produces 
```
{}
```

![image](https://github.com/user-attachments/assets/79ac55b3-1b94-44cd-9e08-0adbd102d585)

Noteworthy: switching to, for example, a model and back to the flow corrects it.

**Comment by MichaelDoyle** [comment]
@tonybaroneee is this the issue we just fixed? :)

**Comment by tonybaroneee** [comment]
> @tonybaroneee is this the issue we just fixed? :)

Yup this is fixed.
