### ISSUE TITLE
[JS] [Vertex AI Plugin] [Vector Search] - bigquery retriever is reported as not working

### ISSUE THREAD

**Issue by cabljac** [firebase/genkit#776]
**Describe the bug**
I've opened this issue to track a bug discussed in the discord. 

**To Reproduce**
Set up and run the test app at js/testapps/vertexai-vector-search-bigquery 

For some users this is not working correctly, it isn't returning results.

**Expected behavior**

**Screenshots**

**Runtime (please complete the following information):**
 - OS: [e.g. Linux, MacOS]

** Node version
 -  run `node --version` at paste here

**Additional context**

**Comment by ssbushi** [comment]
Update: The problem is with the index type -- it must be using the "Stream" update method. Fix is to update the documentation.

**Comment by cabljac** [comment]
https://github.com/firebase/genkit/blob/main/docs/plugins/vertex-ai.md#indexers-and-retrievers

note the docs do mention this already, however i will add to the README of the testapp
