### ISSUE TITLE
[JS] Repackage Genkit NPM packages

### ISSUE THREAD

**Issue by apascal07** [firebase/genkit#783]
**Describe the bug**
`genkit-cli` should become the CLI. `genkit` should become the meta package for all Genkit framework packages (currently `genkit-ai`). `npx create-genkit` should become an alias for `genkit init`.

**Comment by cabljac** [comment]
I've opened a PR to rename `@genkit-ai` scope to `@genkit`. Do we really want to rename `genkit` to `genkit-cli`? 

To me at least, `npm install -g genkit` seems nicer than `npm install -g genkit-cli`

**Comment by cabljac** [comment]
nvm, i see why it is useful to switch to -cli

**Comment by pavelgj** [comment]
duplicate https://github.com/firebase/genkit/issues/390
