### ISSUE TITLE
[JS] Firebase Genkit: how to set system / user /assistant chat history?

### ISSUE THREAD

**Issue by agGitHub** [firebase/genkit#845]
Hi,

May you help about this question :

https://stackoverflow.com/questions/78933726/firebase-genkit-how-to-set-system-user-assistant-chat-history

Thanks a lot !

**Comment by MichaelDoyle** [comment]
Sure @agGitHub, we'll see you over on SO. Posted an answer for you there.

**Comment by agGitHub** [comment]
> Sure @agGitHub, we'll see you over on SO. Posted an answer for you there.

Thanks Michael. But I would like to use a structure like this:

```
const multiTurnPrompt = promptRef('nameOfPrompt');

const result = await multiTurnPrompt.generate({

 model: llama3x70b, 

 history: [
    { role: 'user', content: [{ text: 'Hello.' }] },
    { role: 'model', content: [{ text: 'Hi there!' }] },
  ],

});
```

As can be seen [here](https://firebase.google.com/docs/genkit/dotprompt.md#multi-turn_prompts_and_history) in the doc.

How to do that ?
