### ISSUE TITLE
Firebase Genkit privacy policy ?

### ISSUE THREAD

**Issue by agGitHub** [firebase/genkit#849]
Hello,

I dont' manage to find details concerning the Firebase Genkit privacy policy. Namely, I don't manage to know how input and output data is used by Google. Is input or output data used  by Google for marketing purposes or for training the models ? Any retention of the data ? etc....

Thanks.

**Comment by MichaelDoyle** [comment]
Hey @agGitHub Terms of Service (ToS) is going to vary by model and/or provider. You'll need to refer to the model provider's specific terms. Here are the policies for the Google providers:

- Google AI: https://ai.google.dev/gemini-api/terms
- Vertex AI: 
  - Google Models are subject to cloud terms: https://cloud.google.com/terms/service-terms
  - 3P models such as Anthropic, Llama, etc may have different terms that you will accept when enabling the model

**Comment by agGitHub** [comment]
@MichaelDoyle Thanks for your answer. What about the privacy when using for example Groq through a GenKit plugin ? https://github.com/TheFireCo/genkit-plugins/blob/main/plugins/groq/README.md

**Comment by MichaelDoyle** [comment]
The same principle applies; any data sent to a 3rd party would be subject to the terms of that specific service provider (in this case Groq).

**Comment by agGitHub** [comment]
@MichaelDoyle Thanks for your reply. Not clear in my mind: if I use Groq plugin, Groq terms apply => ok. But do Google AI, Firebase GenKit, Google Gloud or more general Google terms apply ? Does Google use the data for marketing or Ai training purposes ? Thanks.

**Comment by MichaelDoyle** [comment]
Hey @agGitHub, I can't give you specific legal advice, but I will address your question as best as I can. You should consult with your available legal council and/or refer you to each products specific ToS for more information on how data is or isn't used.

The TL;DR, though, is that no data is going to pass through Google services specifically on their way to Groq. i.e. we are not proxying these requests, so there are no Google terms that would apply to your usage of Groq _specifically_.

The complexity here is that you will likely be building an application composed of many parts (i.e. plugins) and each will come with their own separate ToS. For example, you might use Firebase for the "trace" store, Pinecone for a vector store and Google AI for your generative AI model. In that case, your interactions with each of those would have separate terms. _You would need to sign up specifically for each service individually and accept it's terms before you can integrate it._ Genkit is not in the middle of that at all. For example, you would need to accept Google AI's terms before you can get an API key, and then you would provide that API key in your configuration.

The way to think about this is exactly the same as if you went and separately downloaded the Firebase, Pinecone and Google AI SDKs and integrated all of these into your application on your own.

Keep in mind, Genkit is an open source code _library_. It's just  there to help you compose various services together through standardized interfaces. For example, models, vector stores, etc. The Genkit library _itself_ does not collect any data, and it's totally possible and reasonable to use Genkit without interacting with any Google services _at all_ if you choose.

**Comment by pavelgj** [comment]
@MichaelDoyle explained it well. Just want to highlight the bit at the end which is the most important part: Firebase Genkit is a library (code that you use in your app code), it's a not a hosted service. So when you're interacting with Firebase Genkit library itself it's all happening in your code wherever you run it, Firebase/Google does not handle/see your data. Plugins are different, they might be sending your data to a 3P service (ex. vertexai plugin send data to vertexai, groq plugin sends data to groq, etc.)
