### ISSUE TITLE
List of models available with genkitx-groq ?

### ISSUE THREAD

**Issue by agGitHub** [firebase/genkit#850]
In the example [here](https://thefireco.github.io/genkit-plugins/docs/plugins/genkitx-groq), we can see some examples with some models:

llama3x70b
openMixtral8x22B
etc...

What is the complete list of models available ?

Thanks.

**Comment by MichaelDoyle** [comment]
Hey @agGitHub since this is a 3P plugin, I would refer you to the developer's Github repo: https://github.com/TheFireCo/genkit-plugins.

That said, it looks like the current list is:

```
'llama-3-8b'
'llama-3-70b'
'mixtral-8-7b
'gemma-7b
```

See also: https://github.com/TheFireCo/genkit-plugins/blob/main/plugins/groq/src/groq_models.ts#L128-L132
