### ISSUE TITLE
Support Google AI Finetuned Models

### ISSUE THREAD

**Issue by i2amsam** [firebase/genkit#878]
Support for [fine-tuned models](https://ai.google.dev/gemini-api/docs/model-tuning/tutorial?lang=python) in the GoogleAI plugin.

Currently I get this error trying to call a finetuned model

```
    const llmResponse = await generate({
      prompt: `Suggest an item for the menu of a ${subject} themed restaurant`,
      model: 'googleai/tunedModels/my-news-summarizer-apbm8oqbvuv2',
    });
```

```
  "result": {
    "error": "Model \"googleai/tunedModels/my-news-summarizer-apbm8oqbvuv2\" not found",
    "stacktrace": "Error: Model \"googleai/tunedModels/my-news-summarizer-apbm8oqbvuv2\" not found
        at /Users/samphillips/dev/samples/take2/node_modules/@genkit-ai/ai/lib/generate.js:513:13
        at Generator.next (<anonymous>)    
        at fulfilled (/Users/samphillips/dev/samples/take2/node_modules/@genkit-ai/ai/lib/generate.js:43:24)    
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
```

**Comment by i2amsam** [comment]
@MichaelDoyle  points out that this works if the model is provided in the config block

```
    const llmResponse = await generate({
      prompt: `Suggest an item for the menu of a ${subject} themed restaurant`,
      model: gemini15Flash,
      config: {
        version: "tunedModels/my-news-summarizer-apbm8oqbvuv2",
      },
    });
 ```

**Comment by chrisraygill** [comment]
> [@MichaelDoyle](https://github.com/MichaelDoyle) points out that this works if the model is provided in the config block
> 
> ```
>     const llmResponse = await generate({
>       prompt: `Suggest an item for the menu of a ${subject} themed restaurant`,
>       model: gemini15Flash,
>       config: {
>         version: "tunedModels/my-news-summarizer-apbm8oqbvuv2",
>       },
>     });
> ```

@i2amsam this looks like a pretty good experience to me. Does it work the same way for both Google AI and Vertex AI?

cc @cabljac @pavelgj
