### ISSUE TITLE
CORS issue  with "onFlow"

### ISSUE THREAD

**Issue by neo-xy** [firebase/genkit#896]
### Related issues

**node:** v20.9.0

**firebase-functions:**5.0.0

**firebase-tools:**13.16.0

**firebase-admin:**13.16.0

### [REQUIRED] Test case

fireabase functions code:

`configureGenkit({
    plugins: [
        firebase(), // Add projectId here
        vertexAI(),
    ],
    logLevel: "debug",
    enableTracingAndMetrics: false,
});

export const getMenu3 = onFlow(
    {
        name: "getMenu3",
        inputSchema: z.string(),
        outputSchema: z.string(),
        authPolicy: firebaseAuth((user) => {
        }),

    },
    async (subject) => {
        const prompt =
            `Suggest an item for the menu of a ${subject} themed restaurant`;
        const llmResponse = await generate({
            model: gemini15Flash,
            prompt: prompt,
            config: {
                temperature: 1,
            },
        });
        return llmResponse.text();
    }
);
`

Angular code:
`  async textAI() {
    try {
      let ccc = httpsCallable(this.functions, "getMenu3")
      let b = await ccc("banana");
      console.log(b)
    } catch (e) {
      console.log(e);
    }
  }`

### [REQUIRED] Steps to reproduce

- Create Angular application with above code and deploy do fierbase hosting.
- Create Firebase function in the same firebase project with above code. and deploy it as well

### [REQUIRED] Expected behavior

error free response from getMenu3 

### [REQUIRED] Actual behavior

Error:
I replaced name of the project with -> aaa-bbb-ccc  

> Access to fetch at 'https://us-central1-aaa-bbb-ccc.cloudfunctions.net/getMenu3' from origin 'https://aaa-bbb-ccc.web.app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
us-central1-aaa-bbb-ccc.cloudfunctions.net/getMenu3:1 
        
        
       Failed to load resource: net::ERR_FAILED
main-73FIL5CQ.js:32 FirebaseError: internal

### Were you able to successfully deploy your functions?

No did not.

**Comment by tonybaroneee** [comment]
Hey @neo-xy, could you try adding this `httpsOptions` block to your `onFlow` configuration?

```
{
    name: "getMenu3",
    inputSchema: z.string(),
    outputSchema: z.string(),
    authPolicy: firebaseAuth((user) => {
    }),
    httpsOptions: {
        cors: true,
    },
```

**Comment by chrisraygill** [comment]
Tony's [solution](https://github.com/firebase/genkit/issues/896#issuecomment-2377279756) should address this issue. Closing as resolved.
