### ISSUE TITLE
[Tooling] Dev UI doesn't work well on small screens

### ISSUE THREAD

**Issue by mbleigh** [firebase/genkit#904]
From a report of a user in IDX:

> Genkit UI doesn't work well on small screens like a 15" macbook laptop. Scrolling was hit or miss and therefore I missed critical UI elements like the results textbox.

We should make sure the UI is usable or has other affordances to work on reasonable laptop screens (mobile-size screens is probably not a high priority but maybe someday...).

**Comment by i2amsam** [comment]
There are two issues here:

1. Generally, the DevUI doesn't scale down well to smaller widths
2. When embedded in VCCode the DevUI's fonts / ems are larger than the surrounding code, making it take even more space than if you were doing local dev in Chrome.

I'd prioritize 2 first, 1 will take some design thinking through to make sure we have all the right cases covered

**Comment by tonybaroneee** [comment]
We're working on some re-designs to make the Developer UI easier to use in smaller windows. Stay tuned!

**Comment by tonybaroneee** [comment]
We're in a good place now post- nav revamp. Any small tweaks will be tracked in separate tickets.
