### ISSUE TITLE
[Go] When using the dotprompt plugin with a `ModelName` config, it will panic

### ISSUE THREAD

**Issue by dhiaayachi** [firebase/genkit#932]
**Describe the bug**
When creating a prompt with a `ModelName` Config, the provided model name is not considered and it will panic. This is due to a bug when looking up the model in:

https://github.com/firebase/genkit/blob/2940fd520ebde799c74581921546b655b2cab898/go/plugins/dotprompt/genkit.go#L207-L225

The `model` is shadowed inside the if statement and result to the lookedup model going out of context after the if statement.

**To Reproduce**

```golang
prompt, _ := dotprompt.Define("menu", `Suggest an item for the menu of a {{ type }} themed restaurant`, dotprompt.Config{ModelName: "googleai/gemini-1.5-flash", InputSchema: r.Reflect(Input{}), OutputSchema: os, OutputFormat: ai.OutputFormatJSON})

resp, _ := prompt.Generate(ctx,
			&dotprompt.PromptRequest{
				Variables: input,
				Config:    &ai.GenerationCommonConfig{Temperature: 1},
			},
			nil,
		)
```

**Expected behavior**

When a model name is provided, either use the provided model name or return an error if the model lookup fails.

**Runtime (please complete the following information):**
Not relevant

** Go version
Not relevant

**Additional context**
The panic will happen in line:

https://github.com/firebase/genkit/blob/2940fd520ebde799c74581921546b655b2cab898/go/plugins/dotprompt/genkit.go#L227

This is similar to https://github.com/firebase/genkit/issues/847 but not quite the same issue.

**Comment by dhiaayachi** [comment]
I think the fix is pretty simple, just replacing 

```golang
model := ai.LookupModel(provider, name)
```

with

```golang
model = ai.LookupModel(provider, name)
```

Please confirm and I can open a PR with the fix.

**Comment by yukinagae** [comment]
@dhiaayachi Hi, I was able to reproduce the error you mentioned. It seems you're right about both the cause and the solution. I think it's a good idea to create a PR for it.

It would also be better to write an additional test, similar to the one below, to ensure that passing a `ModelName` config works as expected:
https://github.com/firebase/genkit/blob/main/go/plugins/dotprompt/genkit_test.go#L46
